### ISSUE TITLE
注明依赖 Pillow 的版本

### ISSUE THREAD

**Issue by TTsdzb** [Yuri-YuzuChaN/maimaiDX#101]
`libraries/image.py` 第 33 行使用了 `PIL.ImageFont.FreeTypeFont.getsize` 方法：

```python
w, h = font.getsize(text)
```

然而这个方法在 `Pillow` 的 `10.0.0` 版本被移除了。如果直接安装最新的包，会报错：

```
ERROR: 'FreeTypeFont' object has no attribute 'getsize'
```

建议在 README 中标明使用 `Pillow==9.5.0`，或使用其他方法替代。

**Comment by Yuri-YuzuChaN** [comment]
已修复 https://github.com/Yuri-YuzuChaN/maimaiDX/commit/f787b102dacb3e02aba6e6c3cab031f70d84747c ，使用 `getbbox` 函数等同于获取文字大小
