### ISSUE TITLE
无法提交别名投票

### ISSUE THREAD

**Issue by TTsdzb** [Yuri-YuzuChaN/maimaiDX#102]
如图所示，bot 提示添加成功，但找不到投票，也可以重复提交。

![-58d4c81abbe6ae63](https://github.com/Yuri-YuzuChaN/maimaiDX/assets/62687036/438e7a70-009c-48d8-bd99-664c332650e2)

bot 后台没有任何报错。可能需要检查一下服务端？

**Comment by Yuri-YuzuChaN** [comment]
奇怪了，得等我回家在看了

**Comment by Yuri-YuzuChaN** [comment]
已修复
