### ISSUE TITLE
b50图片的DX分数问题

### ISSUE THREAD

**Issue by TTsdzb** [Yuri-YuzuChaN/maimaiDX#103]
b50的DX分数位置显示的是取整后的得分，而不是DX分。

**Comment by TTsdzb** [comment]
![1](https://github.com/Yuri-YuzuChaN/maimaiDX/assets/62687036/b887f8c6-1a52-4f5a-876e-f4068e0d694c)

**Comment by Yuri-YuzuChaN** [comment]
个别人的查分器查询后就是这个分数

**Comment by TTsdzb** [comment]
已可以确认是Bot数据更新器（<https://maimai.bakapiano.com/#/bot/>）的原因。使用水鱼的代理工具无此问题。
