### ISSUE TITLE
[feat] 接入xray机厅API

### ISSUE THREAD

**Issue by TTsdzb** [Yuri-YuzuChaN/maimaiDX#104]
xray 群刚刚公布了机厅人数 API的文档。

所有 bot 使用一个集中的机厅 API 可以在不同的群同步机厅状态，为广大玩家带来便利。

**Comment by Yuri-YuzuChaN** [comment]
不打算接入，已有计划自己做

**Comment by TTsdzb** [comment]
自己做的话还不如像现在这样本地存储了 →_→ 因为自己做并不能完全发挥这个东西应该实现的价值

就我个人的体验，我加了三个群，每个群都是自己的一种 bot。不同的群因为群友习惯不同，需求不同，必然不会都用同一种 bot。如果大家都是自己的 API，那用户仍然需要对几个 bot 分别上报机厅人数，这功能就没有存在的意义了。

**Comment by Yuri-YuzuChaN** [comment]
我自己的计划是带网页地图的，我也不一定会写，因为我自己一百多个群的bot都不用机厅功能，用的删了机厅的分支，而且现在已经有很多带机厅功能的bot，想查也肯定优先找多人用且专门查的和自己本地群自己搭的bot
