### ISSUE TITLE
能否添加海外机厅地址数据

### ISSUE THREAD

**Issue by sion934** [Yuri-YuzuChaN/maimaiDX#108]
maimai海外机厅地址数据来源：
https://zenius-i-vanisher.com/api/arcades.php?action=query&series_id=284&game_name=0&name=&country=0&skip_machines=true&skip_pictures=true&skip_visitors=true&skip_comments=true

其他街机游戏的机厅地址数据：
https://zenius-i-vanisher.com/js/arcades.js

**Comment by Yuri-YuzuChaN** [comment]
这个就不做了
