### ISSUE TITLE
疑似一个群只能订阅一个机厅（？）

### ISSUE THREAD

**Issue by 1553767977** [Yuri-YuzuChaN/maimaiDX#109]
![image](https://github.com/Yuri-YuzuChaN/maimaiDX/assets/39228172/07fb2887-4f76-47ee-b6e9-f243770d6f59)

**Comment by luoyeye001** [comment]
删除以下内容可以订阅多个：
    elif arcade.total.group_in_arcade(gid, name):
        msg = f'该群已订阅机厅：{name}'

**Comment by Yuri-YuzuChaN** [comment]
已实现 https://github.com/Yuri-YuzuChaN/maimaiDX/commit/3647ceec84f21796dcddeb862c093204db84ceb5
