### ISSUE TITLE
(Maybe an) Enhancement : Add @retry on communications with diving-fish.com

### ISSUE THREAD

**Issue by ShinokawaRaine** [Yuri-YuzuChaN/maimaiDX#11]
近期使用过程中偶发连接异常导致的b40/b50单次不可用
error log显示 在获取水鱼网站的成绩列表时有概率无法正常获取 返回空值导致无法渲染图片
(btw 腾讯云香港地区的网络 懂得都懂)
因此 建议在与水鱼进行数据交换的环节添加@retry (python package retrying)

**Comment by Yuri-YuzuChaN** [comment]
已实现
