### ISSUE TITLE
有考虑发布到nonebot插件商店吗

### ISSUE THREAD

**Issue by SherkeyXD** [Yuri-YuzuChaN/maimaiDX#110]
如题 可能需要更改项目结构来使其更加符合nonebot插件的格式

**Comment by Yuri-YuzuChaN** [comment]
可能得考虑研究下

**Comment by Yuri-YuzuChaN** [comment]
已发布 nonebot2 商店，并已通过审核，请等待上架插件商店，该项目[地址](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx)
