### ISSUE TITLE
部分歌曲版本分类错误

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [Yuri-YuzuChaN/maimaiDX#112]
例如s∅lips，该歌曲版本为universe+，但被分类至festival![Image_1695356704922.png](https://github.com/Yuri-YuzuChaN/maimaiDX/assets/86163024/7c461ff9-b6c0-4de9-9a71-5910d140ecf4)

![Screenshot_2023-09-22-12-26-04-33_62ace1b7b6c566cf462d1c5b6e5d6c4b.jpg](https://github.com/Yuri-YuzuChaN/maimaiDX/assets/86163024/7e53b5c6-cdb6-4b50-88ca-79eb4a060abc)

**Comment by Yuri-YuzuChaN** [comment]
特供版本就是这样的，国框就是2023

**Comment by Yuri-YuzuChaN** [comment]
一切以水鱼数据为准
