### ISSUE TITLE
建议：本地别名和别名缓存分开存放

### ISSUE THREAD

**Issue by TTsdzb** [Yuri-YuzuChaN/maimaiDX#113]
如题

**Comment by Yuri-YuzuChaN** [comment]
由于查分器曲目Id更换，需要对别名服务器的id进行更换

**Comment by Yuri-YuzuChaN** [comment]
现已全部恢复

**Comment by TTsdzb** [comment]
> 由于查分器曲目Id更换，需要对别名服务器的id进行更换

请问为了避免串别名，是否需要再次清除本地别名缓存文件？

**Comment by TTsdzb** [comment]
> 如果没有添加本地别名的话还是清楚后再获取吧

其实是有本地别名的，但是串了以后用起来更麻烦...

在以后的更新中能否把本地别名和别名缓存分开存放？

**Comment by TTsdzb** [comment]
> 由于查分器曲目Id更换，需要对别名服务器的id进行更换

这个问题还造成了曲绘不对应的问题，需要更新 `static` 文件

**Comment by Yuri-YuzuChaN** [comment]
> > 如果没有添加本地别名的话还是清楚后再获取吧
> 
> 其实是有本地别名的，但是串了以后用起来更麻烦...
> 
> 在以后的更新中能否把本地别名和别名缓存分开存放？

这个后续更新分开保存吧

**Comment by Yuri-YuzuChaN** [comment]
> > 由于查分器曲目Id更换，需要对别名服务器的id进行更换
> 
> 这个问题还造成了曲绘不对应的问题，需要更新 `static` 文件

还在处理

**Comment by Yuri-YuzuChaN** [comment]
已更换资源文件

**Comment by Yuri-YuzuChaN** [comment]
> > 如果没有添加本地别名的话还是清楚后再获取吧
> 
> 其实是有本地别名的，但是串了以后用起来更麻烦...
> 
> 在以后的更新中能否把本地别名和别名缓存分开存放？

已对自添加的别名进行单独保存
