### ISSUE TITLE
使用minfo功能时缺少资源文件

### ISSUE THREAD

**Issue by OsmiumD** [Yuri-YuzuChaN/maimaiDX#114]
查询minfo时报错缺少文件
![image](https://github.com/Yuri-YuzuChaN/maimaiDX/assets/68777776/cdac8df1-c2ad-4534-8a7f-00a7e53aad90)
资源文件从使用方法中的下载节点2下载

**Comment by Yuri-YuzuChaN** [comment]
你这个用的是上古版本了吧

**Comment by OsmiumD** [comment]
我刚刚才pull的nonebot2分支啊

**Comment by OsmiumD** [comment]
![image](https://github.com/Yuri-YuzuChaN/maimaiDX/assets/68777776/7eb9ba39-3285-4c7f-b354-bf7f7f566c44)

**Comment by Yuri-YuzuChaN** [comment]
直接用现在的版本，看了下确实是我这的代码遗留问题，没有跟主分支同步

**Comment by OsmiumD** [comment]
解决了，但是[maimaidx_api_data.py](https://github.com/Yuri-YuzuChaN/maimaiDX/blob/nonebot2/libraries/maimaidx_api_data.py)
第33行和42行的await加了会卡死，删了以后可以正常运行

**Comment by OsmiumD** [comment]
环境是ubuntu20.04.3, python3.8

**Comment by Yuri-YuzuChaN** [comment]
已修复 https://github.com/Yuri-YuzuChaN/maimaiDX/commit/f0241a23350bf3a86961d708165a29738d36b0a8

**Comment by Yuri-YuzuChaN** [comment]
以为还在用 `aiohttp` 模块请求
