### ISSUE TITLE
旧版机厅信息（本地自定义）无法识别/尝试添加新机厅 缺少词条

### ISSUE THREAD

**Issue by FLAG250** [Yuri-YuzuChaN/maimaiDX#115]
输入格式正确情况下：
\modules\maimaiDX\maimai_arcade.py", line 62, in add_arcade
    arcade.total.append(Arcade(**arcade_dict))
  File "pydantic\main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for Arcade
province
  field required (type=value_error.missing)
mall
  field required (type=value_error.missing)
id
  field required (type=value_error.missing)

**Comment by FLAG250** [comment]
对自动生成的机厅文件(新)的相关机厅的alias添加别名可正常使用

但是旧版机厅词典添加了province,mall,id（id设为9999往前 以防撞id）后 格式与新版文件相同 （于arcade文件手动修改后保存 并重启hoshino）
依然无法识别

user:xxxxjr
返回:
@user 没有这样的机厅哦 

后台无报错

**Comment by Yuri-YuzuChaN** [comment]
涉及自添加的机厅可能没那么快修复，在处理中

**Comment by Yuri-YuzuChaN** [comment]
已修复 https://github.com/Yuri-YuzuChaN/maimaiDX/commit/3647ceec84f21796dcddeb862c093204db84ceb5
