### ISSUE TITLE
机厅模块的潜在问题

### ISSUE THREAD

**Issue by TTsdzb** [Yuri-YuzuChaN/maimaiDX#116]
机厅模块可能还有潜在的问题。在 `maimaidx_arcade.py` 中定义的是 `save_arcade`，但 `maimai_arcade.py` 中使用的是 `saveArcade`：

```py
await arcade.total.saveArcade()
```

**Comment by Yuri-YuzuChaN** [comment]
由于涉及到自添加的机厅可能没那么快修复

**Comment by Yuri-YuzuChaN** [comment]
已处理 https://github.com/Yuri-YuzuChaN/maimaiDX/commit/3647ceec84f21796dcddeb862c093204db84ceb5
