### ISSUE TITLE
未订阅机厅不能修改人数这个设计可能会有点增加复杂度

### ISSUE THREAD

**Issue by Kurokitu** [Yuri-YuzuChaN/maimaiDX#119]
感觉可以这个设计其实没太大必要可能会增加复杂度

**Comment by luoyeye001** [comment]
试试用别名去修改人数捏？

**Comment by Kurokitu** [comment]
@luoyeye001  是用别名来着，然后还是提示来着
![image](https://github.com/Yuri-YuzuChaN/maimaiDX/assets/19619713/7a83ba9c-98a6-43e1-be4c-06d2ad1d1019)

**Comment by luoyeye001** [comment]
嘶还能这样？看看后面print什么捏？

**Comment by Yuri-YuzuChaN** [comment]
最好还是订阅吧，如果别名一样就不能同时添加

**Comment by Kurokitu** [comment]
@Yuri-YuzuChaN 我认为可能做个开关比较好，因为对于本地多群组服务来说每个群都要订阅的话可能会麻烦一些

**Comment by Yuri-YuzuChaN** [comment]
> @Yuri-YuzuChaN 我认为可能做个开关比较好，因为对于本地多群组服务来说每个群都要订阅的话可能会麻烦一些

订阅并不是难事
