### ISSUE TITLE
分数列表这里的图片渲染代码是不是有些小问题

### ISSUE THREAD

**Issue by sigaer** [Yuri-YuzuChaN/maimaiDX#120]
![QQ图片20231007111130](https://github.com/Yuri-YuzuChaN/maimaiDX/assets/73508033/1b9bea9a-7404-4e89-ae82-59ec3927931d)
text应该换成line吧
nonebot2分支 image模块

**Comment by sigaer** [comment]
我的问题，wssb

**Comment by Yuri-YuzuChaN** [comment]
`text` 改成 `line`，我今天把所有bug都修一下
