### ISSUE TITLE
nonebot2分支在获取别名列表时报错闪退

### ISSUE THREAD

**Issue by shinyashen** [Yuri-YuzuChaN/maimaiDX#121]
![image](https://github.com/Yuri-YuzuChaN/maimaiDX/assets/90324553/b4a72b86-3734-44e4-9d22-25de3604ffe8)
内置的别名api出现526错误无法正常工作，尝试使用 #66 中提供的alias.json时出现以上错误，并使nonebot2框架闪退。
![image](https://github.com/Yuri-YuzuChaN/maimaiDX/assets/90324553/071c6669-ef27-4c0b-823b-4f38acf0d6ea)

使用Python版本：3.9.13
使用nonebot2框架版本：2.1.0

**Comment by Yuri-YuzuChaN** [comment]
api已恢复
