### ISSUE TITLE
机厅的别名重复逻辑有点问题

### ISSUE THREAD

**Issue by TTsdzb** [Yuri-YuzuChaN/maimaiDX#123]
如图：
![14750d0e444fe60e](https://github.com/Yuri-YuzuChaN/maimaiDX/assets/62687036/f081ef16-6404-449d-9e8a-2077b65a7542)

**Comment by Yuri-YuzuChaN** [comment]
订阅请使用店名

**Comment by TTsdzb** [comment]
（其实这种不打算修复的可以在 close 时选 as unplanned，便于区分一些
