### ISSUE TITLE
'有什么别称‘指令识别优先级导致的问题

### ISSUE THREAD

**Issue by jizhuex** [Yuri-YuzuChaN/maimaiDX#128]
某些曲目，如id514（ヘルシーエンド）因id11284（co5m1c r4ilr0ad）有别称‘514’，无法使用‘514有什么别称’搜索ヘルシーエンド的别称

**Comment by Yuri-YuzuChaN** [comment]
已修复该问题，现在可以用在查询别名时在前面加上 `ID` 以识别为查询指定ID的别名，不区分大小写

例如：
- `id514有什么别称` 查询ID为514的所有别名
- `514有什么别称` 查询别名为514的所有别名，如果没有就继续查询ID
