### ISSUE TITLE
投票服务器无法访问

### ISSUE THREAD

**Issue by TTsdzb** [Yuri-YuzuChaN/maimaiDX#130]
提示证书错误，可能有过期情况

**Comment by Yuri-YuzuChaN** [comment]
不会呀，这个证书才更新过不久，现在正常访问的

**Comment by TTsdzb** [comment]
![Screenshot_2023-10-20-17-01-50-203_com kiwibrowser browser](https://github.com/Yuri-YuzuChaN/maimaiDX/assets/62687036/f2b560ad-6e5e-4005-a9b5-2942cdd40c15)

那是不是续的时候没包含 `vote` 子域名？

**Comment by Yuri-YuzuChaN** [comment]
噢vote啊，看了下确实没有

**Comment by TTsdzb** [comment]
顺便说一下，如果你用 CF 代理，它是自带证书的，不需要在源服务器上启用 HTTPS。如果还是担心不安全可以使用源证书，点左边 `SSL/TLS` 再点源服务器，在那里生成证书然后放到服务器（对应的域名）上。那个证书有效期很长基本不用续。

**Comment by Yuri-YuzuChaN** [comment]
域名过期后在搞了，现在证书确实搞得很乱，都是二级域名证书，目前是能用就行
