### ISSUE TITLE
考虑将开发重心移至NoneBot？

### ISSUE THREAD

**Issue by TTsdzb** [Yuri-YuzuChaN/maimaiDX#131]
两周前 Mrs4s 宣布由于腾讯持续封杀，go-cqhttp 停止维护（具体可以参考[这个 issue](https://github.com/Mrs4s/go-cqhttp/issues/2471)）。而 Hoshino 框架只能与 Onebot 协议通信，在所有的 QQ 机器人客户端无法使用后，Onebot 协议实现就只剩下了 KOOK、微信以及微信公众号。

而对于 NoneBot，它可以通过适配器连接大量不同平台，因此能大幅提升可用性。

**Comment by Yuri-YuzuChaN** [comment]
nonebot2已发布商店，目前正在做官方QQBOT适配，至于其它的适配如果有需要再考虑，例如Kook需要内测没法进行测试

**Comment by TTsdzb** [comment]
> nonebot2已发布商店，目前正在做官方QQBOT适配，至于其它的适配如果有需要再考虑，例如Kook需要内测没法进行测试

Kook 只要在 <https://developer.kookapp.cn/> 新建一个 Bot 就能用了，不需要申请... 内测邀请制是两年前的事了

**Comment by Yuri-YuzuChaN** [comment]
⭐，转ts3后很久没用kook了
