### ISSUE TITLE
考虑一下更详细的铺面详情？

### ISSUE THREAD

**Issue by Tufmoc** [Yuri-YuzuChaN/maimaiDX#132]
一般在使用id查歌的时候是一整张图片，没法获取到歌曲的曲绘
能否加入绿/黄/红/紫/白+id查歌，使用曲绘+文本描述铺面信息，就像米璐库bot一样

**Comment by Yuri-YuzuChaN** [comment]
不考虑，如果需要曲绘可以去查分器获取
