### ISSUE TITLE
分数列表模块的相关咨询

### ISSUE THREAD

**Issue by Dale2003** [Yuri-YuzuChaN/maimaiDX#142]
可以问一下作者能不能尝试把分数列表那里加上dx分呢，自己尝试半天修改也没能成功，感觉是从水鱼抓的那里的数据没有dx分（
以及作者有没有打算做一个ap50模块或者把分数列表做一个UI  十分感谢！

**Comment by Dale2003** [comment]
还有minfo也没有dx分，可不可以尝试加一下哇qwq

**Comment by Yuri-YuzuChaN** [comment]
dx分必须得有开发者token才能获取

**Comment by Dale2003** [comment]
啊 好的 感谢作者大大！
