### ISSUE TITLE
B50指令和绘制牌子完成表指令异常

### ISSUE THREAD

**Issue by howfer** [Yuri-YuzuChaN/maimaiDX#146]
带牌子的话，提示找不到牌子的图片文件，但是图片文件路径都是没错的

**Comment by Yuri-YuzuChaN** [comment]
请发log

**Comment by howfer** [comment]
![QQ截图20240607223232](https://github.com/Yuri-YuzuChaN/maimaiDX/assets/35104973/04dd5492-c811-447e-bb61-be6cb0918306)

**Comment by Yuri-YuzuChaN** [comment]
文件路径确定是对的吗

**Comment by howfer** [comment]
对的
![QQ截图20240607224148](https://github.com/Yuri-YuzuChaN/maimaiDX/assets/35104973/bcf0d8e8-dddd-4ffc-9c7f-cf4a373b186b)

**Comment by Yuri-YuzuChaN** [comment]
你看下是否有权限

**Comment by howfer** [comment]
权限也是正常的

**Comment by Yuri-YuzuChaN** [comment]
你尝试新建一个 `.py` 文件放在 `maimaiDX` 目录下面，把这下面的内容粘贴进去，然后执行一下这个 `.py` 看还会不会出现文件不存在

``` python
from pathlib import Path
from PIL import Image

root = Path(__file__).parent
platedir = root / 'static' / 'mai' / 'plate'

Image.open(platedir / '熊.png')
```

**Comment by howfer** [comment]
问题已查明  系文件在系统中是乱码的  但是在FTP软件上正常显示   感谢
