### ISSUE TITLE
你可能写错了FULL SYNC+勋章的名称

### ISSUE THREAD

**Issue by Xian0Grem** [Yuri-YuzuChaN/maimaiDX#149]
当某曲目玩家拥有FULL SYNC+的勋章时将无法生成成绩
后台报错 FileNotFoundError: [Errno 2] No such file or directory: 'F:\\HoshinoBot\\HoshinoBot\\hoshino\\modules\\maimaiDX\\static\\mai\\pic\\UI_CHR_PlayBonus_SP.png'

我在资源文件没有找到UI_CHR_PlayBonus_SP.png 这个文件
或许是UI_CHR_PlayBonus_FSP.png这个文件？
我下载的确实是最新的静态资源文件

**Comment by Yuri-YuzuChaN** [comment]
如果是 `FULL SYNC+` 用的图片是 FSp

**Comment by Yuri-YuzuChaN** [comment]
如果是单纯的 `Sync Play`，`minfo `只会用到 `UI_CHR_PlayBonus_Sync.png` 图片
