### ISSUE TITLE
不明白到底是哪出错了 全新安装的LTSC2021 Python3.8SSL报错

### ISSUE THREAD

**Issue by Tufmoc** [Yuri-YuzuChaN/maimaiDX#157]
![Snipaste_2024-09-16_03-45-15](https://github.com/user-attachments/assets/17ea644a-261c-470f-8f62-3294cf475850)
![Snipaste_2024-09-16_03-46-33](https://github.com/user-attachments/assets/d6a7f629-4d67-4146-afab-9519f7dbbfe6)
就是没法通过HTTPS

**Comment by Yuri-YuzuChaN** [comment]
这个得自己找下原因了
