### ISSUE TITLE
查分器DNS无法解析，牵连别名服务器报错

### ISSUE THREAD

**Issue by Clyde-Li** [Yuri-YuzuChaN/maimaiDX#159]
diving-fish.com的DNS解析挂了
https://github.com/Diving-Fish/maimaidx-prober/issues/145#issuecomment-2470081484
测试在bot本地手动添加host有用：
43.154.149.78        www.diving-fish.com

但更新maimai数据时仍有报错：
File "maimaiDX\libraries\maimaidx_api_data.py", line 143, in transfer_music
    return await self._request('GET', self.MaiAliasAPI + '/maimaidxmusic')
  File "maimaiDX\libraries\maimaidx_api_data.py", line 47, in _request
    raise ServerError
hoshino.modules.maimaiDX.libraries.maimaidx_error.ServerError: 别名服务器错误，请联系插件开发者

推测在api.yuzuchan.moe本地临时添加DNS解析或可解决。

**Comment by Yuri-YuzuChaN** [comment]
`Windows Server 2022` 和 `Ubuntu 22` 修改完hosts经测试都是正常访问别名服务器
