### ISSUE TITLE
b50功能中改变歌曲名长度时歌曲名必定带…

### ISSUE THREAD

**Issue by Pr0pHesyer** [Yuri-YuzuChaN/maimaiDX#19]
https://github.com/Yuri-YuzuChaN/maimaiDX/blob/3451630791c7366348a56bf49c2f4c93bb402ab2/libraries/maimai_best_40.py#L294

https://github.com/Yuri-YuzuChaN/maimaiDX/blob/3451630791c7366348a56bf49c2f4c93bb402ab2/libraries/maimai_best_40.py#L245

这两处if似乎有逻辑有问题，可能强制为true，导致b50中即使歌曲名较短也会在其后加上“…”

**Comment by Yuri-YuzuChaN** [comment]
已修复
