### ISSUE TITLE
缺少数据

### ISSUE THREAD

**Issue by Jikexiaobai** [Yuri-YuzuChaN/maimaiDX#22]
比如：紫id11213
则返回：未找到该谱面
但id11213就有

**Comment by Yuri-YuzuChaN** [comment]
已修复该问题，目前查分网站未更新难易度参考tag，故造成该问题，[问题源码](https://github.com/Yuri-YuzuChaN/maimaiDX/commit/16671c12aa3dba2bcf8cfc8dd4a84d97b393f8b1#diff-f84ace03a10eeeed4c1b722e219dbfca9c4da13d4914704df31df9bb1ba126afR62)

**Comment by Jikexiaobai** [comment]
好的，十分感谢
