### ISSUE TITLE
部分歌曲出现错误

### ISSUE THREAD

**Issue by baka-onichan** [Yuri-YuzuChaN/maimaiDX#25]
比如id 11008 
无法输出信息
![QQ截图20220405161708](https://user-images.githubusercontent.com/101969230/161710457-44cb8fcc-ef8d-4d27-a716-ad02bb76e9d5.png)

**Comment by Yuri-YuzuChaN** [comment]
这个极有可能是包含敏感词，被tx吞了发不出消息

**Comment by baka-onichan** [comment]
去掉了艺术家一行，就展示出来了  这歌的作者被TX和谐

**Comment by baka-onichan** [comment]
艺术家那行尾部加了个空格就能正常输出了  感谢提供思路
