### ISSUE TITLE
DX2022 V1.20相关上游改动

### ISSUE THREAD

**Issue by ghost** [Yuri-YuzuChaN/maimaiDX#34]
## 水鱼在资源包里把别名文件扬了 (aliases.csv)

缓解方法: Commit https://github.com/Yuri-YuzuChaN/maimaiDX/commit/9d6f009445fe8429ee7914b3da785b3be14f905e 里有一个旧版的资源包 里面有对应文件

> [下载链接](https://wwa.lanzouq.com/iYjEy010dlne)

## 上游修改了生成b40时2021dx图的id

目前资源报包单独用最新版/单独用旧版/新版覆盖旧版/旧版覆盖新版都出现了无法在b40中加载部分五位id的2021dx图的问题
经查上游改用四位id代表dx图

相关上游commit:
https://github.com/Diving-Fish/mai-bot/commit/3bea2d558aef0bf0fe916e6b4257d38cdeba60a4

**Comment by Yuri-YuzuChaN** [comment]
已做2022[修改](https://github.com/Yuri-YuzuChaN/maimaiDX/commit/0d363e584d796ddb6d96378ab1ab87e03200947f)，别名文件暂时用我服务器做直链
