### ISSUE TITLE
关于分数列表

### ISSUE THREAD

**Issue by howfer** [Yuri-YuzuChaN/maimaiDX#36]
柚子好，更新后，2022的新歌无法显示在列表里

**Comment by Yuri-YuzuChaN** [comment]
例如？

**Comment by howfer** [comment]
例如14分数列表 2022更新的歌都不显示在列表里

**Comment by Yuri-YuzuChaN** [comment]
已修复该问题 https://github.com/Yuri-YuzuChaN/maimaiDX/commit/fc8cd94d6535a4259c2992d722bd9ba647a9fb09

**Comment by howfer** [comment]
谢谢柚子，已解决
