### ISSUE TITLE
如何科学解决插件用不了的问题

### ISSUE THREAD

**Issue by LuRenDing2020** [Yuri-YuzuChaN/maimaiDX#37]
ERROR: Failed to import and load "hoshino.modules.maimaiDX.maimai", error: No module named 'retrying'

但事实上我已经装了retrying

**Comment by Yuri-YuzuChaN** [comment]
是否装了多py环境

**Comment by LuRenDing2020** [comment]
无 只有py3.8

**Comment by Yuri-YuzuChaN** [comment]
依赖问题我就不知道了，你直接把 `maimaidx_music.py` 第 `5` 和 `208` 行删了吧
