### ISSUE TITLE
关于minfo使用别名查询的问题

### ISSUE THREAD

**Issue by howfer** [Yuri-YuzuChaN/maimaiDX#39]
![微信截图_20220915164832](https://user-images.githubusercontent.com/35104973/190359631-1ad7d5a8-820a-4100-9b8d-9e5f02dd9924.png)
柚子好，使用minfo 别名会报错 不知道是什么原因

**Comment by Yuri-YuzuChaN** [comment]
已修复 https://github.com/Yuri-YuzuChaN/maimaiDX/commit/0182784c42b63378013c8210891b4d1639adafb5

**Comment by howfer** [comment]
已解决
