### ISSUE TITLE
查询乐曲信息功能无法使用

### ISSUE THREAD

**Issue by Zya-MATO** [Yuri-YuzuChaN/maimaiDX#40]
![Y5@2O UMHFW8{CBI 6E~DWX](https://user-images.githubusercontent.com/98643379/190578907-41e48700-ed2d-4131-b451-60fcb513a103.png)
使用查询乐曲信息功能时出现如图所示报错

**Comment by Yuri-YuzuChaN** [comment]
我这复现不出来，查询其它谱面是否也是这个情况，因为返回的信息是空的

**Comment by Zya-MATO** [comment]
> 我这复现不出来，查询其它谱面是否也是这个情况，因为返回的信息是空的

查询其他歌曲以及难度也是回报这个错误

**Comment by Yuri-YuzuChaN** [comment]
那发送个 `随个14` 或者 `今日舞萌` 的指令看看会不会报错

**Comment by Zya-MATO** [comment]
> 那发送个 `随个14` 或者 `今日舞萌` 的指令看看会不会报错

这两个指令都没有报错

**Comment by Yuri-YuzuChaN** [comment]
已修复该问题 https://github.com/Yuri-YuzuChaN/maimaiDX/commit/702dc814063b9fb3c5796e1fb44d0780452308be
