### ISSUE TITLE
关于B40B50显示歌曲ID的问题

### ISSUE THREAD

**Issue by howfer** [Yuri-YuzuChaN/maimaiDX#41]
在B40和B50下，DX谱ID显示异常，ID会缺失首位的1 比如11126变成了 1126

**Comment by Yuri-YuzuChaN** [comment]
已修复该问题 https://github.com/Yuri-YuzuChaN/maimaiDX/commit/4c5d6a6774d14670c8c915e0889c9fa19208e128
