### ISSUE TITLE
无法处理消息

### ISSUE THREAD

**Issue by yuyueamatsuki** [Yuri-YuzuChaN/maimaiDX#42]
按照readme部署好后，hos提示导入成功但无法处理命令
![Screenshot_20221016-002938_Microsoft_远程桌面.png](https://user-images.githubusercontent.com/86163024/195997671-5eefc84d-017b-478b-a775-2335161654d0.png)
![Screenshot_20221016-004037_Microsoft_远程桌面.png](https://user-images.githubusercontent.com/86163024/195998017-64b01661-9691-49d1-96f5-eab01136d1eb.png)

**Comment by BlueDeer233** [comment]
其他插件是否正常运行

**Comment by Yuri-YuzuChaN** [comment]
![image](https://user-images.githubusercontent.com/65105396/195998776-ea3500a6-226d-4154-b40a-6ccfdcb31b3f.png)
手动开启，如果要默认开启就把 `enable_on_default` 改成 `True`，然后去 `C:\Users\Administrator\.hoshino\service_config\maimaiDX.json` 文件把 `enable_on_default` 改成 `true`
https://github.com/Yuri-YuzuChaN/maimaiDX/blob/e7a0697f3674fbe06eb04dbe22c9f3ef98fff2f0/maimai.py#L57
