### ISSUE TITLE
B40/B50无法正常使用

### ISSUE THREAD

**Issue by Ezrealkila** [Yuri-YuzuChaN/maimaiDX#45]
再次麻烦柚子了，大佬辛苦了。这次是更新了最新的nonebot和aiocqhttp，nonebot为1.9.1、aiocqhttp也是最新的，但是其他功能能正常使用就是B40/B50无法正常使用结果为下持续了国服DX2个小版本了。
![RHK%F3O0EZROT4I351KF2~Y](https://user-images.githubusercontent.com/106989446/208592547-c0e05a72-b1ea-450c-820a-f7c292acbc2c.png)

**Comment by Yuri-YuzuChaN** [comment]
没下静态资源

**Comment by Ezrealkila** [comment]
> 

好的，排查一下路径弄明白了，我是直接把下载的静态文件直接解压到根目录，没注意到里面的文件，已经搞定了，非常感谢大佬百忙之中抽空回答！十分感谢！
