### ISSUE TITLE
别名文件问题

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [Yuri-YuzuChaN/maimaiDX#47]
目前的别名文件过于老旧，如何手动更新别名文件？
如把fufubot的别名收集表导出为csv但无法读取
[fufubot歌曲别名收集表](https://docs.qq.com/sheet/DVnJUb0pYeXJxakVk?tab=BB08J3)

**Comment by Yuri-YuzuChaN** [comment]
会考虑做成api，同步所有使用插件的bot

**Comment by Yuri-YuzuChaN** [comment]
已完成修改，别名同步所有Bot
