### ISSUE TITLE
一个小建议和一个小bug

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [Yuri-YuzuChaN/maimaiDX#49]
目前添加别名后会向bot所在的全部群聊发送提示，但有些群聊不是音游群，为了防止打扰其他群友，可否加个群聊白名单？
b40查询成绩图时的小bug，bot名这里多了一个括号![3980bed9eb47c67e.jpg](https://user-images.githubusercontent.com/86163024/221048550-ffee5698-411a-4ae8-82d7-e499835eac5f.jpg)

**Comment by BlueDeer233** [comment]
该bug已于最近一次commit修复

**Comment by Yuri-YuzuChaN** [comment]
那还是把插件默认关闭吧，需要的再开这个插件

**Comment by Yuri-YuzuChaN** [comment]
把路径 `./.hoshino/service_config/maimaiDX.json` 中的 `enable_on_default` 修改成 `false` https://github.com/Yuri-YuzuChaN/maimaiDX/commit/533f04f8f98e2e3ed3d74f9639491269c889e207
