### ISSUE TITLE
猜歌功能相关bug

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [Yuri-YuzuChaN/maimaiDX#50]
如图，完成一次猜歌后进行下一次猜歌提示已有正在进行的猜歌，需开关一次猜歌功能后才可正常使用
![-3c6f15e70214740c.png](https://user-images.githubusercontent.com/86163024/221244670-6c34215d-9882-4661-9b03-a8aa5d444df5.png)

**Comment by Yuri-YuzuChaN** [comment]
已修复 https://github.com/Yuri-YuzuChaN/maimaiDX/commit/ddbd10756b6dc232f9aec008c3d64de263776f56
