### ISSUE TITLE
同意别称人数优化的建议

### ISSUE THREAD

**Issue by hallwaysx14** [Yuri-YuzuChaN/maimaiDX#51]
目前的人数是30人才可以通过，但是实际上群里在同一时间内能看到信息并且乐于回复投票的很难凑齐30人，我建议希望可以下调至10人左右，因为大部分群友本质就是懒并且觉得麻烦（ 然后实际查别称又会埋怨怎么这里这首歌没有这个别称 我看xxxbot都有  有些时候也会出现消息被刷上去大家看不到的情况，目前应该是要丰富曲库的别称，我看很多歌曲的别称都没有，所以希望可以酌情下调一下人数要求。
一些常见别称但未收录的例如:
```
id 11333 南十字
id 11384 泥分
id 11284 星穹铁道
id 11236 六月的雨
id 812 种植园纠纷
```
等等

**Comment by hallwaysx14** [comment]
或者是可以直接通过BOT{SUPERUSERS}所提交的别称 而不需要进行投票

**Comment by Yuri-YuzuChaN** [comment]
这个投票是所有使用这个插件的人都能看到，会考虑下调投票人数

**Comment by Yuri-YuzuChaN** [comment]
已做部分修改，当前为15票，后续也会根据投票人数再后台更改票数 https://github.com/Yuri-YuzuChaN/maimaiDX/commit/2a972273c58083016929a45c22a4643fa1bde679
