### ISSUE TITLE
有没有办法不用投票，bot主直接添加别称

### ISSUE THREAD

**Issue by xiaoxianyu233** [Yuri-YuzuChaN/maimaiDX#53]
另外还有一个问题就是有没有办法解决查看别名没有公网ip或域名的办法 还是说就不管这个了（？）

**Comment by Yuri-YuzuChaN** [comment]
不行，这个是所有插件使用者共用的别名库，不会给这个权限，并且有些别名并不合适，甚至还涉及政建，我已经删除了，如果有些别名不错但是票数没达标的我会直接通过，或者减少通过的投票数。
公网没有的话没有办法，只能用长消息查看了

**Comment by xiaoxianyu233** [comment]
那如果加一个本地用的别名曲库呢）

**Comment by Yuri-YuzuChaN** [comment]
以前就是本地别名库

**Comment by Yuri-YuzuChaN** [comment]
后续更新会提供共用的投票站点，解决bot无公网的问题
