### ISSUE TITLE
在添加新别名的时候提示out of range

### ISSUE THREAD

**Issue by luoyeye001** [Yuri-YuzuChaN/maimaiDX#55]
添加别名 11307 有汝高
class indexerror
indexerror : out of range   

显示错误断点在：
 if alias_name in isexist[0]['Alias']:
        await bot.finish(ev, f'该曲目的别名 <{alias_name}> 已存在，不能重复添加别名')

**Comment by Yuri-YuzuChaN** [comment]
这个没有问题，看看你是不是不能访问别名api

**Comment by luoyeye001** [comment]
是yuzuai.xyz嘛，我使用我的个人电脑和服务器都出现了SSL handshake failed的错误 525，在ping的时候延迟180-260不等，丢包75%
请问如何修改可以让bot保持原有投票功能并使用离线别名库，或者如何修改能让bot仅仅使用本地别名库

**Comment by Yuri-YuzuChaN** [comment]
投票功能也需要通过api，现在已经取消本地别名库了，如果要改的话只能找以前commit的内容修改

**Comment by Yuri-YuzuChaN** [comment]
旧的别名库已经好久好久之前的了，也没有录入新曲
