### ISSUE TITLE
draw_music_info出的曲目信息无法加入msg中

### ISSUE THREAD

**Issue by jizhuex** [Yuri-YuzuChaN/maimaiDX#56]
目前draw_music_info出来的文件是MessageSegment类，无法通过加入到今日舞萌等同时有文字与曲目信息的msg中
报错信息为“TypeError: can only concatenate str (not  MessageSegment） to str
hoshino版本是最新git下来的

**Comment by Yuri-YuzuChaN** [comment]
检查一下 `nonebot` 和 `aiocqhttp` 依赖是不是最新版本
