### ISSUE TITLE
（nonebot2）使用“有什么别名”“是什么歌”命令时报错

### ISSUE THREAD

**Issue by HSAllenbili** [Yuri-YuzuChaN/maimaiDX#57]
使用“有什么别名”“是什么歌”命令时报错
 File "/home/ubuntu/mbot/src/plugins/maimaiDX/maimai.py", line 338, in _
    name = event.get_plaintext().lower().removesuffix(end).strip()
AttributeError: 'str' object has no attribute 'removesuffix'

**Comment by zhanbao2000** [comment]
Python 3.9 才支持 `removesuffix` 方法，参考：
https://docs.python.org/zh-cn/3/library/stdtypes.html#str.removesuffix

我看下有无其他优雅的取代方法

**Comment by zhanbao2000** [comment]
找不到好的方法，用了最传统的`slice`解决（

https://github.com/Yuri-YuzuChaN/maimaiDX/blob/313471994419f27769ad8fc41b5fd7f574b8f99e/maimai.py#L321

https://github.com/Yuri-YuzuChaN/maimaiDX/commit/313471994419f27769ad8fc41b5fd7f574b8f99e
