### ISSUE TITLE
需要全局关闭别称推送功能

### ISSUE THREAD

**Issue by LiebeVerletzt** [Yuri-YuzuChaN/maimaiDX#59]
这样，我是用bot当大号的，插件很多，服务的群非常繁杂，并且有相当一部分没有我另一个SuperUser号在群内，导致前两天更新插件后开始大批量在maimai无关群聊内发送别称推送信息，带来了一定的困扰。
希望能有全局关闭/全局黑名单的功能，至少不用每新进一个群都要连发“启用maimaiDX”和“关闭别称推送”了。
用相关群聊填满了config内的disable，希望能简便点。

**Comment by Yuri-YuzuChaN** [comment]
直接注释这行吧 https://github.com/Yuri-YuzuChaN/maimaiDX/blob/5861a4d24dc42b134eedb2e3fbb2f0bfb76226d6/maimai.py#L405

**Comment by Yuri-YuzuChaN** [comment]
已更新全局关闭推送功能，该指令为BOT管理员私聊指令 https://github.com/Yuri-YuzuChaN/maimaiDX/commit/baec217c2cbe38e8efb1e0c107fe0a7ed6f46f04
