### ISSUE TITLE
bot启动问题

### ISSUE THREAD

**Issue by luoyeye001** [Yuri-YuzuChaN/maimaiDX#60]
[2023-04-21 12:35:51,398 maimaiDX] INFO: 正在获取maimai所有曲目信息
Task exception was never retrieved
future: <Task finished name='Task-14' coro=<CQHttp._handle_event_with_response() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py:606> exception=KeyError('11308')>
不知道是不是因为11308这个歌导致整个曲库无法使用，现在b40b50报
[2023-04-21 12:38:55,082 maimaiDX] ERROR: 'MaiMusic' object has no attribute 'total_list'

**Comment by Yuri-YuzuChaN** [comment]
已修复 https://github.com/Yuri-YuzuChaN/maimaiDX/commit/89736912740ad3ffe27711803ed575fd0f26fc71

**Comment by luoyeye001** [comment]
感谢update，已经解决
