### ISSUE TITLE
能否在别名加入xray-bot的别名库

### ISSUE THREAD

**Issue by SnivyJ** [Yuri-YuzuChaN/maimaiDX#66]
目前内置的别名库过于少，很多歌曲都没有别名，能否加入xray-bot的别名库作为歌曲别名的信息

**Comment by Yuri-YuzuChaN** [comment]
有库的话我可以上传

**Comment by KelsAstell** [comment]
[all_alias.zip](https://github.com/Yuri-YuzuChaN/maimaiDX/files/11485231/all_alias.zip)
转好格式的别名库，json转换工具已经开源。
项目地址：[别急]

**Comment by Yuri-YuzuChaN** [comment]
已更新别名库
