### ISSUE TITLE
有关于token

### ISSUE THREAD

**Issue by luoyeye001** [Yuri-YuzuChaN/maimaiDX#72]
想咨询一下token，是需要专门找水鱼申请吗，还是自助申请的

**Comment by Yuri-YuzuChaN** [comment]
自行私聊水鱼申请

**Comment by luoyeye001** [comment]
btw，在使用minfo功能时，查询b35能正常显示，而b15直接跳未游玩，不知道是否与token有关

**Comment by Yuri-YuzuChaN** [comment]
没有token的情况下用的是查分器的查将牌功能，而现在查分器的牌子选择里还没有星和宙的也就是uni和uni+的版本选择，所以查不到新歌

**Comment by luoyeye001** [comment]
明白了，感谢

**Comment by Yuri-YuzuChaN** [comment]
应该是fes的

**Comment by Yuri-YuzuChaN** [comment]
我确实没加上，这下是我的问题了
