### ISSUE TITLE
牌子查询勘误（可能）

### ISSUE THREAD

**Issue by 1553767977** [Yuri-YuzuChaN/maimaiDX#91]
真代的牌子需求版本为maimai和maimai plus（不需要打id70），模块内部查询真代进度时只显示maimai plus的完成情况，歌曲总数也仅有40来首

**Comment by Yuri-YuzuChaN** [comment]
已修复 https://github.com/Yuri-YuzuChaN/maimaiDX/commit/b5b7586bdde482e3c072390815ac97e105125201
