### ISSUE TITLE
yuzuapi 没有 GetMaimaiDXMusicData 接口

### ISSUE THREAD

**Issue by TTsdzb** [Yuri-YuzuChaN/maimaiDX#96]
<https://api.yuzuai.xyz/maimaidx/GetMaimaiDXMusicData> 直接返回 404。是还没有弄好吗 (。﹏。)

另外关于 #95，我的服务器（阿里云北京）在从 diving-fish 获取数据是总是要花很久。一开始只是获取曲目数据要几分钟时间，我寻思可能返回体太大，就把请求超时改成五分钟凑合用了。但是最近连查分都很慢，同一个群里也是这个插件的 bot 反应比我的快一两分钟。可能不是个例……？

**Comment by Moxiner** [comment]
我一会儿把请求时间改成5分钟试试

**Comment by TTsdzb** [comment]
> 我一会儿把请求时间改成5分钟试试

五分钟不行再试试更长时间，总之获取一次要特别久

**Comment by Yuri-YuzuChaN** [comment]
把Data删了，我写多了

**Comment by Yuri-YuzuChaN** [comment]
目前就只知道阿里和华为对查分器的访问响应是非常长的

**Comment by TTsdzb** [comment]
> 把Data删了，我写多了

好的，稍等一会

**Comment by Yuri-YuzuChaN** [comment]
可以重新pull一下
