### ISSUE TITLE
别名库被污染

### ISSUE THREAD

**Issue by SaigyoujiYusora** [Yuri-YuzuChaN/maimaiDX#98]
翻以前的issue说好像会同步fufubot的别名列表，但那个表格内的id未随查分器ID更新，使用的仍是游戏内实际ID，导致别名串了。

例如询问bot：淘宝是什么歌。

bot会回答：
找到3个相同别名的曲目：
434：taboo tears you up
602：larva
10434：taboo tears you up

.30乐曲列表内，larva ID为746 ，taboo tears you up ID为602
水鱼查分器内，larva ID为 602, 标准taboo tears you up ID为434

**Comment by Yuri-YuzuChaN** [comment]
重新获取别名库
